version: '3.8'

services:
  presencebackend:
    image: presencebackend
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: supersecure123#A
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
