services:
  presence-backend:
    image: ghcr.io/mathisburger/herenow-backend
    ports:
      - "8080:8080"
    volumes:
      - ./appsettings.json:/app/appsettings.json

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    environment:
      MSSQL_SA_PASSWORD: supersecure123#A
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
